import { valueHasPlaceholder, type RuleConfigEntry } from './rule-config';

/**
 * Renders /docs/build/CONFIG-REGISTER.md (CLAUDE.md §2): every configuration
 * point, its rule citations, provenance and resolution status. Regenerated by
 * `pnpm gen:config-register` whenever entries change; RELEASE-READINESS
 * requires zero PLACEHOLDER rows.
 */
export function renderConfigRegister(entries: RuleConfigEntry[], generatedAt: Date): string {
  const rows = [...entries]
    .sort((a, b) => (a.key < b.key ? -1 : 1))
    .map((e) => {
      const status = valueHasPlaceholder(e.value) ? '**PLACEHOLDER**' : 'set';
      const value = valueHasPlaceholder(e.value) ? '—' : `\`${JSON.stringify(e.value)}\``;
      return `| \`${e.key}\` | ${e.ruleIds.join(', ')} | [${e.source}] | ${status} | ${value} | ${e.description} |`;
    });

  const placeholderCount = entries.filter((e) => valueHasPlaceholder(e.value)).length;

  return `# CONFIG-REGISTER.md — Rule Configuration Register
**Generated:** ${generatedAt.toISOString()} — do not edit by hand; run \`pnpm gen:config-register\`.

Placeholders remaining: **${placeholderCount}** (production refuses to start unless this is 0 — CLAUDE.md §2).

| Key | Rule IDs | Source | Status | Value | Description |
|---|---|---|---|---|---|
${rows.join('\n')}
`;
}
